---
criticalpatterns:
      - '[Aa]bort|ABORT'
      - '[Ee]rror|ERROR'
      - '[Ff]atal|FATAL'
      - 'Oops:'
      - 'kernel: .* BUG:'
      - 'kernel: .*megaraid mbox: reset sequence completed sucessfully'
      - 'kernel: .*sd.* Unhandled sense code'
      - 'kvm: .* cpu.* unhandled (rd|wr)msr'

criticalexceptions:
      - 'ACPI Error: Method parse/execution failed'
      - 'ansible-file: Invoked with'
      - 'apache.*00_error_documents.conf'
      - 'api: .*ValueError.*No JSON object could be decoded'
      - 'auxpropfunc error invalid parameter supplied'
      - 'auxpropfunc error no mechanism available'
      - 'awstats:.*All HTTP errors with last referrer'
      - 'bandersnatch\[mirror\]: '
      - 'btrfs: ERROR: failed to open'
      - 'budget: .* HTTPConnectionPool.*: Max retries exceeded'
      - 'build-kernel: Enable recovery from hardware memory errors'
      - 'build-kernel: .*Preparing to merge modules'
      - 'caused the error.</p>'
      - 'charts: .*Error'
      - 'chronyd.*: Set system time error in RTC'
      - 'claimx.*:'
      - 'clxmci: socket.error'
      - 'Configuration Error. Please fix your configfile'
      - 'configure/kvm: configure/kvm failed: exit status'
      - 'configure/kvm: .*ProtocolError for .*: 502 Proxy Error'
      - 'configure/kvm: .*raise error'
      - 'configure/kvm: socket.error'
      - 'configure/users: .*RuntimeError.*EEXISTS'
      - 'configure/zones: .*ProtocolError for .*directory: -1'
      - 'configure/zones: .*raise error'
      - 'configure/zones: socket.error'
      - 'consul.* agent: failed to sync (changes|remote state): rpc error'
      - 'consul.* dns: rpc error'
      - 'consul.* http: Request .*error: No known Consul servers'
      - 'consul.* raft: aborting pipeline replication to peer'
      - 'consul.* Request .* error: No cluster leader'
      - 'consul.* Request .* error: Permission denied'
      - 'consul.* Request .* error: rpc error'
      - 'consul.* Watch .* errored: Unexpected response code'
      - 'convert: unable to read font'
      - 'Could not retrieve file metadata for puppet'
      - 'dd.collector.*: ERROR'
      - 'dd.dogstatsd.*: ERROR'
      - 'dd.forwarder.*: ERROR'
      - 'dd.forwarder.*: WARNING .* Transaction .* in error'
      - 'dev-libs/libgpg-error'
      - 'dev-perl/Error'
      - 'directory2.api.*: end_maintenance.*result.*error'
      - 'directory\.accounting: .*urllib2\.URLError'
      - 'directory\.prices: gocept\.collmex\.collmex\.APIError'
      - 'directory\.prices:.*(urllib2|urlopen|URLError|HTTPError)'
      - 'curator: ERROR. No indices matched provided args'
      - 'ERROR: .* failed to (start|stop)'
      - 'Error in sys.excepthook:'
      - 'ERROR: .* is already (starting|stopping)'
      - '_error.log'
      - 'error: PAM: Authentication failure'
      - 'ERROR: \(rs_job_iter\) internal error: job made no progress'
      - 'error was encountered while trying to use an ErrorDocument to handle the request'
      - 'FATAL:\s+terminating connection due to administrator command'
      - 'freshclam.*: connect_error'
      - 'ftpd.*: .*NOTICE.*downloaded'
      - 'generate-stage4:.*'
      - 'glsa: @ERROR: max connections .* reached -- try again later'
      - 'glsa: @ERROR: Unknown module.*gentoo-portage'
      - 'glsa: rsync error: some files/attrs were not transferred'
      - 'glsa: rsync error: (timeout in data send/receive|error starting client-server protocol)'
      - 'grub: ERROR: ld.so: object.*from LD_PRELOAD cannot be preloaded'
      - '<h1>Error'
      - 'haproxy.*: Server .* is DOWN'
      - 'hg: abort: .* [Ee]rror'
      - 'howslow: '
      - '(imap|pop3).*: Deleted mailbox'
      - '(imap|pop3).*: ERROR: message has more than 1000 header lines'
      - '(imap|pop3).*: Expunged .* messages from'
      - '(imap|pop3).*: Fatal error: tls_start_servertls.* failed'
      - '(imap|pop3).*: IOERROR: opening .*/cyrus.header: No such file or directory'
      - '(imap|pop3).*: IOERROR: reading message: unexpected end of file'
      - '(imap|pop3).*: IOERROR: stating header'
      - '(imap|pop3).*: open: user .* opened'
      - 'in the server error log\.'
      - 'jazzforum/superoffice-sync'
      - 'jugpro00 cynin: '
      - 'karl_.*: .*ERROR zc.lockfile'
      - 'karl_.*: .* INFO'
      - 'karl_.*:.*LockError'
      - 'karl.*postoffice: .*Message-Id'
      - 'karlserve.scripts.feeds:'
      - 'kernel: .* ACPI Error.*Method parse/execution failed'
      - 'kernel: .* ACPI Error.*Namespace lookup failure'
      - 'kernel: .* (apache|grub|gs|doctotext|soffice.bin).*: segfault'
      - 'kernel: .* conftest.*: segfault at .* in'
      - 'kernel: .* connection.*: detected conn error'
      - 'kernel: .* error_code\+0x'
      - 'kernel: .*ERROR.* drm/i915 can.t work without intel_agp module'
      - 'kernel: .*EXT4-fs error .*: ext4_lookup'
      - 'kernel: .* fc-qemu.* segfault at .* error 4 in librbd.so.1.0.0'
      - 'kernel: .* GPT: Use GNU Parted to correct GPT errors'
      - 'kernel: .* icmpv6_send: no reply to icmp error'
      - 'kernel: .* IPMI Watchdog: response: Error .. on cmd 22'
      - 'kernel: .* PCIe errors handled by platform firmware'
      - 'kernel: .* pmacctd.*: segfault at'
      - 'kernel: .* timsieved.*: segfault at'
      - 'kernel: .* traps: atop.* trap divide error'
      - 'kernel: .* wget.* general protection'
      - 'kernel: .* (wget|jenkins).*: segfault'
      - 'kernel: .* wvWare.*: segfault .* in libwv'
      - 'ListError.* No such file or directory'
      - 'lms-zeo:.*An error occurred'
      - 'lms-zeo:.*Server Error'
      - 'lmtpunix.*: Delivered: <.*@.*> to mailbox'
      - 'lmtpunix.*: duplicate_check: <.*@.*>'
      - 'lmtpunix.*: duplicate_mark: <.*@.*>'
      - 'lmtpunix.*: ERROR: message has more than 1000 header lines'
      - 'lmtpunix.*: IOERROR: fstating sieve script .*: No such file or directory'
      - 'lmtpunix.*: sieve runtime error.*Fileinto: Mailbox does not exist'
      - 'logcheck/apache_error_log'
      - 'logcheck/.*log_errors.cfg'
      - 'lvm.*: Initialised segtype: error'
      - 'lvm.*: Setting activation/missing_stripe_filler to error'
      - 'makewhatis: bzcat: I/O or other error bailing out'
      - 'makewhatis:  Input file = .* output file ='
      - 'message repeated \d+ times'
      - 'nagios:.*(ALERT|NOTIFICATION|CURRENT.*STATE|ACKNOWLEDGE_SVC_PROBLEM)'
      - 'named.*: client .*: query .*denied'
      - 'named.*: dispatch .*: shutting down due to TCP receive error.*: connection reset'
      - 'named.*: DNS format error from'
      - 'named.*: error \(.*\) resolving'
      - 'named.*: socket.c:.* unexpected error'
      - 'named.*: success resolving .* after'
      - 'no coalesce parameters changed aborting'
      - 'no errors or warnings'
      - 'NPCD.*: ERROR: Command line was '
      - 'NPCD.*: ERROR: Executed command exits with return code'
      - 'nrpe.*: Error: Could not complete SSL handshake'
      - 'pam_ldap: error trying to bind as user.*\(Invalid credentials\)'
      - 'pep381run: (Copying|Synchronizing) '
      - 'pep381run: socket.error:'
      - 'postoffice: .* INFO '
      - 'postoffice: .*KeyError.*No message with key'
      - 'postoffice: Message added to queue'
      - 'postoffice: Message rejected'
      - 'postoffice: .*No such file or directory'
      - 'postoffice: ZODB.POSException'
      - 'pre-commit: [ADMU] .*'
      - 'puppet.*: .*Control-C to abort'
      - 'puppet.*: Could not retrieve catalog.*: Error 400 on SERVER'
      - 'puppet.*: Failed to find .* via exec: .* 503 Service Temporarily Unavailable'
      - 'puppet.*: .*Failed to generate additional resources using .*: Error 500'
      - 'puppet.*: .*[Nn]et_analyzer::.*error_log'
      - 'puppet.*: .*SQLite3::BusyException'
      - 'pure-ftpd.*: .*\[ERROR\] Can.t open .*'
      - 'pure-ftpd.*: .*\[ERROR\] Sorry invalid address given'
      - 'pure-ftpd.*: .*\[ERROR\] Unable to identify the local socket'
      - 'pure-ftpd.*: .*\[INFO\]'
      - 'pure-ftpd.*: .*\[NOTICE\]'
      - 'radvd.*: caught SIGINT aborting'
      - 'radvd.*: ERROR: radvd stopped by something else'
      - 'radvd.*: poll error: Interrupted system call'
      - 'raft: .*Aborting election'
      - 'rc-scripts: ERROR: wrong args'
      - 'rc-scripts: failed please correct errors above'
      - 'rc.*: write: Input/output error'
      - 'rdiff-backup on .* failed with .* soft errors'
      - 'redmine-update.* abort:.*[Ee]rror'
      - 'redmine-update.* abort: no suitable response from remote hg'
      - 'redmine-update/hg: abort: HTTP Error 503: Service Unavailable'
      - 'renderd.*: An error occurred while loading the map layer .*: File does not exist'
      - 'rsync error: error in rsync protocol data stream'
      - 'rsync error: error in socket IO'
      - 'rsync error: received SIGINT SIGTERM or SIGHUP'
      - 'rsync error: syntax or usage error'
      - 'rsync.*: getpeername on fd6 failed'
      - 'rsync-glsa.*: ERROR: exceeded max retries'
      - 'rsync.*: rsync error: received SIGINT SIGTERM or SIGHUP'
      - 'rsync.*: read error'
      - 'rt4:.* failed--compilation aborted'
      - 'RT: RT thinks this message may be a bounce'
      - 'RT: WebRT: '
      - 'run-awstats: Warning: Error while retrieving hashfile'
      - 'run-crons.*: .* CMD'
      - 'Running.*embed /boot/grub/.*failed \(this is not fatal\)'
      - 'run-update-puppet.*: .*cacheddir.*EmptyOnError'
      - 'run-update-puppet.*: .*Control-C to abort'
      - 'run-update-puppet.*: .*dev-(perl|libs)/.*[Ee]rror'
      - 'run-update-puppet.*: .*Error fetching binhost package info'
      - 'run-update-puppet.*: .*ftp error.*Can.t change directory'
      - 'run-update-puppet.*:  \* WARNING!'
      - 'saslauthd.*: do_auth *: auth failure:.*PAM auth error'
      - 'sievelocal.*: login: localhost'
      - 'sieve.*: .* syntax error'
      - 'slowlog: Thread .*: Started on .*; Running for'
      - 'SpecialFileError.* Socket error'
      - 'sshd.*: error: accept: Software caused connection abort'
      - 'sshd.*: error: connect_to .*: failed'
      - 'sshd.*: error: Could not load host key: /etc/ssh/ssh_host_ecdsa_key'
      - 'sshd.*: error: PAM: Error in service module for illegal user'
      - 'sshd.*: error: (RSA_public_decrypt|ssh_msg_send)'
      - 'sshd.*: fatal: Read from socket failed'
      - 'sshd.*: fatal: (Write|Read) failed: Connection reset by peer'
      - 'sshd.*: Invalid user .* from'
      - 'sshd.*: Read error from remote host'
      - 'sshd.*: Received disconnect from .*: do_connect error'
      - 'sshd.*: syslogin_perform_logout: logout.* returned an error'
      - 'stunnel: .* Error detected on socket'
      - 'superoffice-sync: mx.ODBC.Error.OperationalError'
      - 'superoffice-sync: mx.ODBC.Error.ProgrammingError'
      - 'syslog-ng.*: Error processing log message:'
      - 'timeout: abort: error'
      - 'trafficclient.*: An error occurred but last update is within grace period ignoring'
      - 'transportpedia:'
      - 'tvsxavm:'
      - 'UpdateError.*(librsync error|Updated mirror temp file)'
      - 'update-repositories: abort: no suitable response'
      - 'varnishd.*: Child .* Panic message: Missing errorhandling code in sma_alloc'
      - 'varnishd.*: Pushing vcls failed: CLI communication error'
      - 'vixie-cron.*: ERROR: vixie-cron failed to start'
      - 'watchdog.*: write watchdog device gave error 22'
      - 'webmaster@gocept.com and inform them of the time the error occurred'

warningpatterns:
      - 'Can.t load firmware'
      - 'DEPRECATION NOTICE'
      - '[Ff]ail|FAIL'
      - 'kernel: .* apparmor=.* denied_mask='
      - 'kernel: .* invoked oom-killer:'
      - 'kernel: .* nf_conntrack: table full'
      - '[Uu]nexpected.*[Ee]xception'
      - '[Ww]arn]|WARN'
      - 'xinetd.*: Unknown user'

warningexceptions:
      - '0 failures 0 errors'
      - 'ACPI _OSC support notification failed disabling PCIe ASPM'
      - 'acpi PNP.*: fail to add MMCONFIG information'
      - 'atd.*: Open of jobfile failed: Broken pipe'
      - 'audit: .* apparmor="ALLOWED"'
      - 'bandersnatch.* (INFO|DEBUG):'
      - 'bandersnatch.package WARNING: Checksum error with local file'
      - 'btrfs: total \d failures'
      - 'build-kernel: .*\(MEMORY_FAILURE\)'
      - 'build-kernel: .*Print quota warnings to console'
      - 'claimx.*:'
      - 'clxmci: '
      - 'clxmmmci: '
      - 'codebackup: Failed to back up'
      - 'codebackup: WARNING: the following repositories failed to update'
      - 'collectd.*: Filter subsystem: Built-in target .*write.*: Dispatching value to all write plugins failed with status -1.'
      - 'collectd.*: processes plugin: Failed to read from'
      - 'collectd.*: read_file_contents'
      - 'collectd.*: write_graphite plugin'
      - 'configure/kvm: configure/kvm failed: exit status 1'
      - 'configure/users failed: exit status 1'
      - 'configure/zones: configure/zones failed: exit status 1'
      - 'consul.* agent: failed to sync'
      - 'consul.* agent: Join failed'
      - 'consul.* consul.rpc: multiplex conn accept failed'
      - 'consul.* dns: node .* failing health check'
      - 'consul.* Failed to push local state'
      - 'consul.* Failed to send ping'
      - 'consul.* failed to sync remote state'
      - 'consul.* Marking .* as failed'
      - 'consul.* member.* [Ff]ailed'
      - 'consul.* Push/Pull with .* failed'
      - 'consul.* raft.*Aborting election'
      - 'consul.* raft.*: Failed'
      - 'consul.* serf: EventMemberFailed'
      - 'consul.* serf: Failed to re-join any previously known node'
      - 'consul.* skipping reconcile of node'
      - 'consul.* Suspect .* has failed'
      - 'consul.* yamux: Failed to write header'
      - 'curator: .*WARNING.* No indices matched provided args'
      - 'dd.collector.*: WARNING'
      - 'dd.dogstatsd.*: WARNING'
      - 'dd.forwarder.*: WARNING'
      - 'dovecot: imap.*: Warning: .* Duplicate file entry'
      - 'dovecot: master: Warning: .* is no longer mounted'
      - 'ERROR: .* failed to (start|stop)'
      - 'ERROR: .* is already (starting|stopping)'
      - 'exception.*Failed to send UDP packet'
      - 'EXT4-fs .*: ext4_check_descriptors: Checksum for group .* failed'
      - 'Failed publickey for.*ssh2'
      - 'Failed to retrieve current state of resource: No package found with the specified name'
      - 'failfast='
      - 'fail_on_user='
      - 'failover support'
      - 'Fast TSC calibration failed'
      - 'freshclam.* Incremental update failed trying to download daily.cvd'
      - 'generate-stage4.*fine but exhibit random runtime failures'
      - 'generate-stage4.*openpty failed:.*out of pty devices'
      - 'generate-stage4.*parser/functions/fail.rb'
      - 'generate-stage4.*Please do .*not.* report compilation failures'
      - 'generate-stage4.*warnings or failures related to missing symbols'
      - 'howslow: '
      - 'If the server still fails to shutdown'
      - 'imap.*: imaps TLS negotiation failed'
      - '(imap|pop3).*: badlogin: .* authentication failure'
      - '(imap|pop3).*: Fatal error: tls_start_servertls.*failed'
      - '(imap|pop3).*: (imaps|pop3s) failed'
      - '(imap|pop3).*: .* in SSL_accept\(\) -> fail'
      - '(imap|pop3).*: SSL_accept\(\) interrupted by signal.* -> fail'
      - '(imap|pop3).*: SSL_accept\(\) timed out -> fail'
      - '(imap|pop3).*: STARTTLS negotiation failed'
      - '(imap|pop3).*: warning: cant get client address: Connection reset by peer'
      - 'imap.*: SQUAT .*failed'
      - 'jenkins.* kernel: .* invoked oom-killer'
      - 'karl.*: .*urlopen error'
      - 'karl.*: .*WARNING karlserve.log: No instance is set'
      - 'karl.*: .*WARNING karlserve.scripts.main'
      - 'kernel: .*ACPI Error: Method parse/execution failed'
      - 'kernel: .*acpi PNP.* _OSC failed.*; disabling ASPM'
      - 'kernel: .*ata.*: failed to resume link'
      - 'kernel: .*Failed to access perfctr msr'
      - 'kernel: .* ICMPv6 checksum failed'
      - 'kernel: .* nfsd: peername failed'
      - 'kernel:.*PM: Resume from disk failed'
      - 'kernel: .*sd[a-z].* Asking for cache data failed'
      - 'kernel: .*svc: failed to register lockdv1 RPC service'
      - 'kernel: .*tsc: Marking TSC unstable due to check_tsc_sync_source failed'
      - 'kernel: .*usb .*: uhci_result_common: failed with status 440000'
      - 'kernel: .*WARNING: at drivers/iommu/intel_irq_remapping.c'
      - 'kernel: .*WARNING: CPU: .* PID: .* at drivers/dma/ioat/dca.c'
      - 'kernel: .*: WRITE SAME failed. Manually zeroing.'
      - 'kvm: _sasl_plugin_load failed on .* for plugin: (ldapdb|sql)'
      - 'lmtpunix.*: verify_user.* failed: (Over quota|Mailbox does not exist)'
      - 'lvm.*: dm_task_run failed'
      - 'maintenance.* \(req .*\) returned TEMPFAIL'
      - 'message repeated \d+ times'
      - 'nagios:.*(ALERT|NOTIFICATION|WARNING|CURRENT .* STATE)'
      - 'named.*: client .*: query .* denied'
      - 'named.*: DNS format error from.*invalid response'
      - 'named.*: error \(unexpected RCODE .*\) resolving'
      - 'named.*: managed-keys-zone.*: loading from master file .* failed: file not found'
      - 'named.*: managed-keys-zone.*: Unable to fetch DNSKEY set .*: SERVFAIL'
      - 'named.*: success resolving .*after'
      - 'named.*: \s*validating @.*: www.dnssec-failed.org NSEC'
      - 'named.*: unexpected RCODE .*SERVFAIL'
      - 'named.*: .*validating .* verify failed due to bad signature'
      - 'named.*: zone .* refresh: failure trying master .* operation canceled'
      - 'named.*: zone .* unchanged'
      - 'NPCD.*: WARN: MAX load reached: load'
      - 'oira.doc: .* WARNING'
      - 'Otherwise any SSL validation that use the directory may fail'
      - 'PAM: Authentication failure'
      - 'pam_unix\(sudo:auth\): (authentication failure|conversation failed)'
      - 'pep381run: (Copying|Synchronizing) '
      - 'pop3.*: \[pop3d\] STARTTLS failed'
      - 'postgresql.* Shutting down the server gracefully failed'
      - 'postoffice: .* INFO repoze.postoffice:'
      - 'puppet.*: Failed to find.*/etc/puppet/node.rb.*returned [12]'
      - 'puppet.*: Failed to load library.*selinux'
      - 'puppet.*: Not using cache on failed catalog'
      - 'puppet.*: .*stage4[ _]failed[ _]builds'
      - 'pure-ftpd.*: .*\[ERROR\] Can.t open'
      - 'pure-ftpd.*: .*\[INFO\]'
      - 'postoffice: Message added to queue'
      - 'postoffice: Message rejected'
      - 'pure-ftpd.*: .*\[NOTICE\]'
      - 'radvd.*: WARNING: radvd has already been started'
      - 'radvd.*: WARNING: radvd is already starting'
      - 'rbd: .* WARNING: kernel layering is EXPERIMENTAL!'
      - 'rc-scripts: WARNING: .* has already been (started|stopped)'
      - 'rc-scripts: WARNING: .* has not yet been (started|stopped)'
      - 'rdiff-backup on .* failed with .* soft errors'
      - 'rngd: failed fips test'
      - 'rpc.statd.*: Failed to read /var/lib/nfs/state: Success'
      - 'rsyncd.*: .*Connection reset by peer'
      - 'rsyncd.*: forward name lookup for .* failed'
      - 'rsyncd.*: name lookup failed for '
      - 'rsync: failed to connect to'
      - 'rsync: getpeername on fd. failed'
      - 'rsync: writefd.* failed to write'
      - 'rt4: Compilation failed'
      - 'rt4:.* failed--compilation aborted'
      - 'RT: Encode::Guess failed'
      - 'RT: FAILED LOGIN for'
      - 'RT: .*Failed to downgrade'
      - 'run-awstats: Warning: Error while retrieving hashfile'
      - 'run-maintenance.*: \(req .*\) returned TEMPFAIL suspending'
      - 'Running.*embed /boot/grub/.*failed \(this is not fatal\)'
      - 'saslauthd.*: DEBUG: auth_pam:'
      - 'saslauthd.*: do_auth *: auth failure:.*PAM auth error'
      - '_sasl_plugin_load failed on sasl_auxprop_plug_init for plugin:'
      - 'servercept: LOGIN to SIEVE server failed for'
      - 'sieve.*: badlogin: .*(LOGIN|PLAIN) authentication failure'
      - 'slapd.*: entry failed schema check: object class .starAlliancePerson. requires attribute .cn'
      - 'slapd.*: WARNING: slapd is stopping'
      - 'slowlog: Thread .* Started on .* Running for .* secs'
      - 'sshd.*: Disconnecting:'
      - 'sshd.*: error: connect_to .* port .*: failed'
      - 'sshd.*: Failed keyboard-interactive/pam for'
      - 'sshd.*: fatal: Read from socket failed'
      - 'sshd.*: Invalid user .* from'
      - 'sshd.*: pam_unix.*: (authentication failure|conversation failed)'
      - 'sshd.*: Received disconnect from .*:'
      - 'sshd.*: reverse mapping checking getaddrinfo for .* failed'
      - '[sS]phinx.*/templates/autosummary.* WARNING: document isn.t included in any toctree'
      - 'staralliance.users.scripts: .*WARN'
      - 'superoffice-sync: mx.ODBC.Error.ProgrammingError'
      - 'syncthing: .*WARNING: Folder .* isn.t making progress'
      - 'tvsxavm: .* WARNING'
      - 'update-bacula-clients: warning: cannot find vm .* in Ceph'
      - 'update-repositories:.*(add|delete).* mode .*(warn|fail)'
      - 'WARNING: .* has already been started'
      - 'WARNING Init Class .* has a security declaration for nonexistent method .*'
      - 'WARNING: .* is already (starting|stopped)'
      - 'WARNING: .* is deprecated and will be removed in the future'
      - 'WARNING: net.* has started but is inactive'
      - 'WARNING Products.PloneHotfix20121106 Could not apply random_string'
      - 'WARNING: .*you are stopping a boot service'
      - 'WARNING: Your ClamAV installation is OUTDATED'
      - 'xinetd.*: FAIL: (nrpe|lmtp) address from'
      - 'xinetd.*: FAIL: nrpe connections per second'
...